// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptxvazldIq9tountHtha9wispOtBNVpg',
    appId: '1:359631759790:web:269f2859570d66e963403f',
    messagingSenderId: '359631759790',
    projectId: 'plantmanagerapp-eac9f',
    authDomain: 'plantmanagerapp-eac9f.firebaseapp.com',
    storageBucket: 'plantmanagerapp-eac9f.firebasestorage.app',
    measurementId: 'G-RE3DKFJZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpy4qf-iyoKe_2xTxfN4YCaprnuA3rpZQ',
    appId: '1:359631759790:android:ee6db2a862e6977d63403f',
    messagingSenderId: '359631759790',
    projectId: 'plantmanagerapp-eac9f',
    storageBucket: 'plantmanagerapp-eac9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykgV5i2usEfJfq_rdyzSZrwe_EQKyeDM',
    appId: '1:359631759790:ios:5c7e8d2e7820358563403f',
    messagingSenderId: '359631759790',
    projectId: 'plantmanagerapp-eac9f',
    storageBucket: 'plantmanagerapp-eac9f.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykgV5i2usEfJfq_rdyzSZrwe_EQKyeDM',
    appId: '1:359631759790:ios:5c7e8d2e7820358563403f',
    messagingSenderId: '359631759790',
    projectId: 'plantmanagerapp-eac9f',
    storageBucket: 'plantmanagerapp-eac9f.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAptxvazldIq9tountHtha9wispOtBNVpg',
    appId: '1:359631759790:web:2b406cdb07c3759563403f',
    messagingSenderId: '359631759790',
    projectId: 'plantmanagerapp-eac9f',
    authDomain: 'plantmanagerapp-eac9f.firebaseapp.com',
    storageBucket: 'plantmanagerapp-eac9f.firebasestorage.app',
    measurementId: 'G-49DWHFEK29',
  );
}
